# Generated by Django 2.2 on 2021-12-06 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0008_auto_20211206_1221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='retweets',
        ),
        migrations.DeleteModel(
            name='TweetRetweet',
        ),
    ]
