# Generated by Django 2.2 on 2021-12-10 19:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0010_auto_20211209_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweetcomment',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
