# Generated by Django 2.2 on 2021-12-10 20:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0011_auto_20211210_2116'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tweetcomment',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterModelOptions(
            name='tweetlike',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterField(
            model_name='tweetcomment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
